@startuml
!define table(x) class x << (T,#FFAAAA) >>
!define primary_key(x) <u>x</u>
hide methods
hide stereotypes

table(users) {
    uid: integer
    email: string
    password: bytea
    first_name: string
    last_name: string
}

table(calendar) {
    uid: integer
    name: string
    event: big integer
    owner_uid: integer
}

table(events) {
    uid: integer
    from_calendar_uid: integer
    to_calendar_uid: integer
    text: string
    datetime: datetime
}

calendar -> users
events -> calendar
@enduml
