"""rev1

Revision ID: e19131f45850
Revises: 6bb8c22058cf
Create Date: 2020-12-02 17:58:52.786831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e19131f45850'
down_revision = '6bb8c22058cf'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.Binary(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('calendar',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('case', sa.BigInteger(), nullable=True),
    sa.Column('owner_uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('events',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('from_calendar_uid', sa.Integer(), nullable=True),
    sa.Column('to_calendar_uid', sa.Integer(), nullable=True),
    sa.Column('text', sa.BigInteger(), nullable=True),
    sa.Column('datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['from_calendar_uid'], ['calendar.uid'], ),
    sa.ForeignKeyConstraint(['to_calendar_uid'], ['calendar.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('calendar')
    op.drop_table('users')
    # ### end Alembic commands ###
